In [1]:
import sys

In [2]:
sys.version

'3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [11]:
claim = pd.read_csv('C:/Users/Ali/Documents/CIBC/claims_final.csv', header=None, names=['family_id','member_id', 'provider_id', 'provider_type', 'state', 'date', 'procedure', 'amount'])

In [12]:
print(claim)

         family_id  member_id  provider_id  provider_type state      date  \
0           518632          0         9929      122398719    NY  20060719
1           327546          0         2299      122398719    NY  20060526
2           342944          5         5367      122398782    NY  20060817
3           342944          5         5367      122398782    NY  20060717
4            72526          0         9029      122398719    NY  20060221
5           234943          1        10215      122398719    FL  20060615
6           375277          2         3939      122398719    NY  20060413
7            55460          0        14582      122398719    NY  20060413
8           534991          0        14685      122398719    CA  20060531
9           493892          2          639      122398719    NY  20060714
10          216339          2        13246      122398719    CA  20060308
11          459386          1        14259      122398719    NY  20060719
12           65172          1         2697      122398719    NY  20060813
13          227605          1        15754      122399961    FL  20051012
14           99208          2        13058      122398719    NY  20060819
15          512614          0        14145      122398719    CA  20060815
16          329846          0         4796      122398719    FL  20060705
17           32683          1        14140      122398719    NY  20060702
18          539874          4        11328      122398719    CA  20060809
19          198824          0         7879      122398719    CA  20060413
20          506925          3          336      122398719    TX  20060802
21           85082          2        12795      122398719    NY  20060714
22          326622          2        14980      122398719    NY  20060627
23          334226          1         8576      122398719    NY  20060801
24          527147          0        15633      122398719    NY  20060720
25          180793          0         4016      122398807    NY  20060802
26           39554          2        15582      122398719    NY  20060710
27          466770          0         8530      122398719    NY  20060628
28          373550          3        18607      122398719    FL  20060717
29          346888          2        11072      122398719    NY  20060515
...            ...        ...          ...            ...   ...       ...
3497713     521637          1         8531      122398719    NY  20060815
3497714     315701          2         8662      122398719    NY  20060801
3497715     315701          2         8662      122398719    NY  20060801
3497716      13824          0        11895      122398719    NY  20060801
3497717     210299          1         8682      122398719    NY  20060801
3497718     349916          2        10715      122398782    NY  20060814
3497719     401261          0         6879      122398719    NY  20060815
3497720     539916          0        18665      122398719    CA  20060706
3497721     295920          0         3156      122398719    NY  20060801
3497722     456382          2        16323      122398719    CA  20060807
3497723     143109          1        16142      122399961    FL  20060731
3497724     259892          2         9945      122398719    NY  20060706
3497725      56022          1         8243      122398719    NY  20060801
3497726     326349          0        16473      122398719    NY  20060814
3497727     237953          0         6817      122398719    NY  20060730
3497728     516409          2         8263      122398794    NY  20060815
3497729     160725         21         8379      122398719    NY  20060730
3497730     259802          0        15269      122398719    NY  20060730
3497731     455067          0         6839      122398719    NY  20060814
3497732     220802          3        13890      122398719    NY  20060814
3497733     543967          2         3535      122398782    NY  20060331
3497734     416372          0         7148      122398719    CA  20060815
3497735     137828          0        18293      122398719    NY  20060730
3497736     534430          0         6848      122398719    NY  20060730
3497737     234803          1        12807      122398719    FL  20060814
3497738     146492          0        10670      122398719    NY  20060801
3497739     146492          0        10670      122398719    NY  20060801
3497740     389303          3         2780      122398782    NY  20060227
3497741      41597          0         9265      122398719    NY  20060807
3497742     545260          0         3522      122398769    NY  20060411

         procedure   amount
0              282   707.08
1              280   381.37
2             1688   889.29
3             1688   889.29
4              562  1681.68
5              288   336.63
6              515  1403.40
7              283   942.77
8              278   529.51
9              288   475.65
10             282   610.49
11             283  1054.05
12             278   594.56
13             914  2242.07
14            1320  1193.37
15             282   546.03
16             282   738.52
17             282   288.66
18             515   849.21
19             140   373.88
20            1359  1667.20
21             282   745.32
22             167   586.01
23             140   531.79
24             282   499.98
25            1005  1151.15
26             280   426.38
27             278   531.79
28            1370   879.01
29             280   404.50
...            ...      ...
3497713        138  1172.02
3497714        167   516.37
3497715        297   449.44
3497716         95   484.07
3497717         95   176.94
3497718       1688   984.69
3497719        283  1054.05
3497720        283   772.21
3497721        283   942.77
3497722        282   610.49
3497723       1205   258.18
3497724        282   745.32
3497725         95   559.56
3497726        169   688.99
3497727        280   426.38
3497728        313   513.43
3497729       1005  1287.02
3497730        282   707.08
3497731        169   688.99
3497732        493  1775.18
3497733       1688  1421.28
3497734        282   546.03
3497735        280   426.38
3497736        282   666.64
3497737         95   786.21
3497738        282   666.64
3497739        288   475.65
3497740       1688  1098.30
3497741        278   594.56
3497742       1623  1534.06

[3497743 rows x 8 columns]